create database company;
use company;
create table EMPL(ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(50),AGE INT,SALARY INT);
Insert into EMPL(NAME,AGE,SALARY) VALUES('ARAVITH',30,15000),('ARUN',25,20000);
Select*From EMPL;
Create Table DEPARTMENT(DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,DEPT_NAME VARCHAR(50));
Insert into DEPARTMENT (DEPT_NAME)VALUES('MANAGAR'),('HR'),('EMPLOYEE');
Select*From DEPARTMENT;
Create Table EMP(EMP_ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(50),DEPT_ID INT,FOREIGN KEY (DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID));
Insert into EMP(NAME,DEPT_ID)VALUES('PAVI',1),('KAVI',2),('RAVI',3);
Select*From EMP;
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
Inner Join DEPARTMENT D
On E.DEPT_ID=D.DEPT_ID;
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
Left Join DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID
Order By E.EMP_ID;
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
Right Join DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID
Order By E.EMP_ID;
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
Cross Join DEPARTMENT D;
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
Left Join DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID
Union
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
Right Join DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID;
Select E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
From EMP E
JOIN DEPARTMENT D;
